---
title: "Shiny_Zooimage_J_29"
output: html_document
---

Fichier de notes du jour 29, jeudi 10 Mars 2022.    Présentiel

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Je vais donc, enfin, après avoir réglé mes problèmes, pouvoir recommencer des tests sur Shiny, golem, et Zooimage.


!!! Afin de comprendre comment mettre au point le système du projet/package golem dans mon repository github, j'ai passé une après midi avec \
M. Grosjean, et j'ai pris des notes dans le Jour_28.txt à propos des étapes à suivre. (notament des changements dans le fichier .Rbuildignore) \
Ou encore des changements dans les options du projet => Build Tools, configure \
J'ai écris les étapes réalisées en gros. \


=== Objectif : Faire une application qui va lire la variable environnementale : va chercher des données dans le dossier correspondant ===

 1) Variable environnementale "ZOOIMAGE_DATA_DIR"
    -> Sys.setenv(ZOOIMAGE_DATA_DIR = "~/shared/data)
    -> Comment utiliser ça dans l'app ? Pramètre de l'app ?


 Questions)
 - Toujours, les variables et autres peuvent-elles passer entre les modules/fichiers de base ?

=========================================================================================================================================

 => App sous golem qui arrive à aller chercher des données de titanic, depuis ~/shared/data/ : Fonctionne !
 

=== Nouvel objectif : Essayer d'utiliser un dossier, en considérant que on utilse l'app en local. ===

 shinyfiles ?

=> Non, il suffit d'aller chercher dans les chemins

L'app, tourne soit sur le serveur, soit en local.

Mais les données, les fichiers et dossiers, sont toujours trouvé en local : local du serveur, ou local du local.

=====================================================================================================



Resumé de mes questions sur golem :

- Peut on créer mettre des modules dans un module ?

- Peut on faire passer des variables d'un module à l'autre ? Il me semble que oui.
