---
title: "Shiny_Zooimage_J_38"
output: html_document
---

Fichier de notes du jour 38. Mercredi 23 Mars 2022. Présentiel.

Il n'y a pas eu de notes durant le jour 37 car j'ai rédigé dans mon rapport de stage partiel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Je continue de rajouter le contenu à mon application.

La création d'un ou plusieurs ZIDB à partir du sample sélectionné, ou de tous, est maintenant possible. \
De plus, on peut voir en temps réel les ZIDB qui extistent déjà. \

! -> J'ai recrée la variable smpfiles dans la fenêtre "Samples" plutôt que de reprendre celle des settings car je dois l'actualiser, et je préfère éviter de lier les deux fenêtres dans un cas où ce n'est pas nécessaire. Les settings n'ont pas besoin de cette info. \

Je vais passer à la visualisation et aux vignettes \


J'ai rajouté le système de visualisation des ZIDB créés. \

Je vais regarder pour ajouter le choix du ZIDB au panneau fixe : Communication à double sens entre deux modules. \
J'ai réussis à le faire fonctionner. \

J'ai regardé avec M. Grosjean afin de check le package, corriger ce qui n'était pas bon (utils, data_folder_path : options(), wordlist)
Ajout des données exemples, dont les training sets en zip pour éviter les chemins d'accès trop long : warnings \


J'ai changé mon système de communication inter modules afin que tous les modules puissent avoir accès à tous les autres, cela simplifie également l'écriture des arguments des différents modules. \
De plus, on peut choisir de tout actualiser à chaque fois en même temps, ou bien uniquement les modules qui varient en séparant les observe() \


En essayant d'implanter le système d'affichage des vignettes, je me suis rendu compte qu'il me faudrait me pencher sur la question des erreurs : \
Il faut que je puisse tester que les fichiers existent, afin de pouvoir les utiliser, et que les fonctions ne s'éxécutent que si les fichiers existent. \