---
title: "Shiny_Zooimage_J_36"
output: html_document
---

Fichier de notes du jour 36. Lundi 21 Mars 2022.    Présentiel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Je vais tout d'abord essayer de regarder pour rajouter les données de test "exemple" du package (que M. Grosjean m'a donné). \
Pas sûr de tout le bon fonctionnement car il s'agit d'anciennes données, sous un ancien format (afin qu'elles ne soient pas d'une taille trop volumineuse pour le format package). \

=> Attention au gitignore et attention au check : marque des messages de "warning" ? :/


Apprentissage du package fs pour utiliser d'une meilleur manière les chemins \
-> fs::path() pour créer un chemin \

Je suis entrain de rajouter le panneau fixe à mon application web. \
Il y a donc deux colonnes dans une ligne, une colonne de taille 2 et l'autre de taille 10 : celle de 2 contient le panneau fixe, et l'autre le contenu de l'app. \


J'ai rajouté du CSS dans mon app : ajout du panneau fixe avec css et ajout de css dans ma colonne de droite. \

Je vais regarder pour ajouter un thème de shiny : package shinythemes \

J'ai donc combiné du css avec un thème de shiny pour rendre mon app plus jolie. \

=> CSS + Theme + Panneau fixe + mise en page et minis modifs


J'ai rajouté un onglet Samples que j'ai repris de ce que j'avais déjà fait dans mon ancienne app de ZooImage, et en la nettoyant car beaucoup de choses n'était plus bonnes, ou au bon endroit. Je vais donc à présent essayer de la rendre fonctionnelle. \
J'ai donc rajouté un module, avec quelques éléments dans tous les fichiers qui s'en occupe. \

J'ai dans ma page Samples un onglet ZIDB Preparation dans lequel il y a : \
- Un sidepanel qui permet de créer le(s) ZIDB avec options \
- Un mainpanel qui permet de voir le contenu de l'échantillon que l'on sélectionne, ainsi que les ZIDB déjà préparés. \

J'ai essayé de rajouter dans le mainpanel un verbatimOutput qui affiche le contenu de l'échantillon choisi, et il faut que je fasse attention que mon CSS influence son affichage. \




