---
title: "Shiny_Zooimage_J_47"
output: html_document
---

Fichier de notes du jour 47. Mardi 05 Avril 2022. Distanciel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

J'ai mis en place le système permettant de créer un training set depuis le mode server. \
Quand on crée un training set, ça le télécharge directement, et le supprime ensuite pour \
ne pas garder un training set non trié sur le server. \

J'ai créé une fonction que je vais tester pour voir si elle fonctionne. \
Elle est sensé vérifier et corriger le nom du training set que je souhaite utiliser. \

Je vais rajouter également un affichage des training sets existants sur le server. \

Ma fonction, fonctionne, par contre j'ai un problème lié au setwd() \
Je remarque qu'en fait elle ne retourne pas comme elle devrait au oldir ... \

J'ai réussis à régler mon problème en utilisant des paramètres à on.exit() add et after : \
        on.exit(unlink(stsp_name(), recursive = TRUE)) \
        on.exit(setwd(oldir), add = TRUE, after = TRUE) \
        
J'ai fait une vérification du R command Check => Tout est en ordre à présent. \
Attention que shinyjs importe spécifiquement ses fonctions (pour ne pas se confondre avec zooimage) \

Je vais à présent introduire le système pour voir l'état du tri pour le mode local et l'upload du mode server. \

J'ai remis le système d'upload de training set pour le mode server. \
Quand on upload, cela le met dans le bon dossier, l'unzip, et supprime l'archive. \

Utilisation de on.exit() \

=> Mettre le système pour voir l'état de tri et des éléments dans la partie visualisation. \
