---
title: "Shiny_Zooimage_J_32"
output: html_document
---

Fichier de notes du jour 32. Mardi 15 Mars 2022. Distanciel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

J'ai réglé un peut les commentaires dans le script pour le dossier des données, \
et j'ai rajouté une valeur de défault pour le chemin du dossier qui est "~/" \

Je vais regarder pour remettre les anciennes partie de l'app que j'avais déjà \
fait dans l'ancienne app de test de ZooImage \

Ajout d'un affichage conditionnel du dossier sample ! \
Bouton qui permet de l'afficher ou non. \
Je vais ensuite essayer de rendre plus réactif la variable globale smpfiles et smps => trop fixe \


J'ai rajouté une option pour définir un dossier "Samples" pour pouvoir ensuite l'utiliser dans ZooImage ! \
On peut voir le contenu des différents dossier, choisir le bon, et le définir. \
On peut le changer si on se trompe. \
Si jamais on change de dossier de data, cela s'actualise. \

Maintenant, les variables smpfiles, et smps qui étaient dans les variables globales sont maintenant dans le module Data_Folder_bis car elle sont plus réactives, elle sont en fait définies par le choix du dossier Sample. \

Je vais maintenant essayer de faire communiquer des modules entre-eux et donc récupérer des variables à travers ceux-ci. \
J'ai essayé de chercher un peu, mais je n'ai pas encore trouvé. \
