---
title: "Shiny_Zooimage_J_43"
output: html_document
---

Fichier de notes du jour 43.    Mercredi 30 Mars 2022.    Présentiel.

Il n'y a pas de notes du jour 42 car j'ai travaillé sur mon rapport partiel de stage et mon projet de poster.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Je vais continuer dans mon application partie training sets.

J'ai rajouté le comptage du nb de lignes de l'échantillon dans les informations globales.

Je suis entrain de mettre en place la préparation de training sets.

Je me rends compte qu'il y a un problème avec des fonctions qui agissent quand elles ne devraient pas.

Bon,

req est à utiliser principalement quand on veut que tout ce qui suit s'arrête. Mais on ne peut pas l'utiliser n'importe comment, car cela arrête vraiment toute la réactivité. \
req considère comme mauvais : FALSE, "", NULL, ... \

il faut plutôt utiliser des if quand on sait qu'on peut avoir différents états, et qu'il faut réagir différemment en fonction de ceux-ci. \

J'ai donc enfin réglé mon problèmes de dépendances : Il faut bien faire attention aux req et if \

J'ai continué à mettre en place la préparation des training sets voir mod training sets \
