---
title: "Shiny_Zooimage_J_54"
output: html_document
---

Fichier de notes du jour 54. Jeudi 14 Avril 2022. Distanciel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

--- Je pourrais rajouter plus tard :
-> Choix de la méthode oob pour le modèle
-> Choix des priors
-> Possibilité de comparaison
-> Il faudrait que je change la mise en place du choix du classifieur dans le panneau fixe

Je regarde à rajouter les éléments importants de la suite de l'application. \

J'ai rajouté un choix pour le sommaire. \

Relecture d'explications par rapport à ZooImage afin de d'introduire la partie results. \

J'ai commencé à créer la page results. \

Mise en place d'un affichage du Sample choisi et du classifieur acitf. \

Indication de si les données sont prêtes à être utilisées par rapport au Sample et au classifieur. \

Tests liés au Sample et classifieur sont réalisés. \
Des messages indiquent ce qu'il manque. \

Mise en place d'une sélection d'un script pour les calculs à effectuer. \

Mise en place du bouton activé ou désactivé en fonction du Sample, du classifieur mais également du script. \
Mise en place d'une fonction qui vérifie le script. \
Mise en place d'un script exemple pour calculer des résultats. \
Mise en place d'un message par rapport au chargement du script et d'un commentaire expliquant le script. \

Mise en place du calcul des résultat et d'un premier affichage de test. \

Ajout de l'affichage du nom du script utilisé. \

Mise en place de l'affichage du script utilisé dans le panneau fixe, et donc de la communication depuis l'onglet results. \

Changement de l'affichage de l'onglet création des résultats. \

Mise en place de nouveaux scripts pour de nouveaux résultats : biomass et spectres de taille. \

J'ai réalisé des recherches afin de voir comment je pourrais rendre les résultats plus visibles par rapport à leur format. \

Je mets en place un système pour sauvegarder et télécharger les résultats. \


J'ai tenté de mettre en place un système pour sauvegarder les résultats. \
Cela semble fonctionner à partir de ma fonction. A confirmer. \

J'ai détecté un problème, l'un de mes scripts pour avoir des résultats est mal écrit, résultat, mon application plante => Il faut que je corrige le script et que je rajoute une vérification afin que l'application ne plante plus pour cette raison. \
Il faut également que je m'assure qu'il y ait assez de commentaires et explications claires dans mon code pour ces dernières parties. \


