---
title: "Shiny_Zooimage_J_55"
output: html_document
---

Notes du jour 55. Vendredi 15 Avril 2022. Distanciel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

J'ai tout d'abord essayer de réparer un problème dans mon application. \
Quand j'éxécute un script, je test différents paramètres liés à ce dernier, mais je ne teste pas si la fonction fonctionne. \
J'ai donc rajouté des tests par rapport au fonctionnement de la fonction. \
Le problème est du côté modèle, où le test prend un peu de temps car la création d'un classifieur prend du temps. \

Je pourrais faire en sorte qu'il ne faille plus créer une deuxième fois le classifieur, mais n'ayant plus beaucoup de temps, je préfère en rester dans cet état où les tests fonctionnent. \

J'ai rajouté quelques commentaires dans la partie Results et dans ma fonction pour sauvegarder. \
Mise en place d'un message plus clair pour la sauvegarde. \

Mise en place du téléchargement des résultats. \

Utilisation d'une fonction. \

Clarifications dans la partie sauvegarde et téléchargement des résultats. \
La vérification du nom ne se fait plus qu'une seule fois, j'ai donc modifié ma fonction pour la sauvegarde des résultats en local. \

J'ai rajouté quelques commentaires. \

J'ai également ajouté une vérification que les results ne soient pas une erreur pour récupérer le nom du résultat. \

J'ai modifié l'affichage de la sauvegarde et du téléchargement. \

----------------------

=> Il faudrait à présent que : \
-> Je trouve un meilleur affichage des résultats. \
-> Je corrige les quelques petits problèmes d'affichage des autres pages. \
-> Mise en place d'idées d'ajouts. \

Après midi : \

Début des améliorations générales \

Idées : \

Meilleur visualisation Sample - \
Meilleur visualisation TS - \
Meilleur visualisation Results - \

Changements dans mes interfaces de mes différentes pages pour rendre le tout plus clair et convivial. \
Changements d'apparitions contrôlées \
