---
title: "Shiny_Zooimage_J_53"
output: html_document
---

Fichier de notes du Jour 53. Mercredi 13 Avril 2022. Distanciel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Je vais continuer à avancer dans mon app. \
=> Partie Models \

J'ai fait quelques vérifications par rapport au build et réparé différents problèmes. \
J'ai également "simplifié" la création de la matrice de confusion. \

Je vais tenter rapidement de faire une fonction qui fait la grosse validation du modèle. \

J'ai donc réussis à transformer mon gros bloc de code en une fonction pour rendre mon code plus court et plus clair ainsi que plus fonctionnel. \

Je vais à présent continuer d'implanter des nouveautés. \

J'ai mis en place un affichage du classifieur actif dans le panneau fixe. \

J'ai rajouté dans la partie visualisation un visionnage des plots en plus d'un navlistpanel pour mieux s'y retrouver. \

J'ai mis en place un système de sauvegarde de classifieur créé, je vais maintenant essayer de mettre en place un chargement. \

J'ai fini de mettre au point le système de sauvegarde et de chargement d'un classifieur. \

J'ai un peu galéré, mais cela fonctionne. \
Le classifieur utilisé est soit celui crée, soit si on en charge un, celui là. \

Je vais ensuite mettre au point un système pour supprimer un classifieur sauvegardé et ensuite continuer pour la suite. \

Attention ! Nom du classifieur pour affichage. \

2 problèmes :
Le bouton pour créer un classifieur ne se remet pas disponible directement.
La réactivité de la liste des classifieurs sauvegardé ne fonctionne pas correctement par rapport aux autres éléments réactifs. \

J'ai réglé tous les problèmes de réactivité, j'avais mal utilisé mon reactiveVal(0!) \

J'ai bien mis en place mon système de suppression de Classifieur sauvegardé. \

J'ai également fait en sorte que le bouton pour créer une classifieur se réactive en fin de création si les inputs sont toujours les bons. \

J'ai rajouté deux scripts exemples. (un avec mlSvm) \

