---
title: "Shiny_Zooimage_J_59"
output: html_document
---

Fichier de notes du jour 59. Vendredi 22 avril 2022. Présentiel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Je vais faire une réunion vers 10h avec M. Grosjean pour montrer les améliorations que j'ai réalisé dans mon application. \

En attendant, je continue d'améliorer mon application. \

J'ai dans Samples, séparé les différents blocs de metadata. \

J'ai rajouté au Summary du zidb sélectionné un choix des attributs à afficher. \

Je modifie certains éléments de css. \


!! Je n'utilise tjrs pas les données d'exemples !!


Continuation de changements par rapport aux dernières remarques de M. Grosjean. \

Changements globaux de titres ou mise en forme de l'affichage. \

J'ai réussis à mettre au point un système où quand l'on change un sélecteur input sur un onglet, cela change la sélection du même sélecteur dans un autre onglet, afin qu'il prenne la même valeur, et de plus, le résultat de ces deux inputs est une même variable, qui prendra la valeur soit de l'un, soit de l'autre, en fonction de qui change ! \

J'ai réussis à mettre au point le même système pour la sélection de TS pour visualisation et pour models. \

J'ai également du corriger un problème de manque de vérifications pour le sample. \
