---
title: "Shiny_Zooimage_J_57"
output: html_document
---

Fichier de notes du jour 57. Mercredi 20 Avril 2022. Distanciel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

J'ai tout d'abord réalisé un nouvel exemple de script pour la création d'un classifieur. \

Ensuite, je me suis lancé dans l'amélioration de mon application par rapport aux différentes remarques de M. Grosjean. \

J'ai tout d'abord commencé par changer la sélection du training set pour la visualisation dans la page training sets. \

J'ai ensuite changé la sélection du training set pour la page Models. \

J'ai changé différents affichages dans le panneau fixe. J'ai mis en place la visualisation de la progression du training set choisi dans la visualisation, et pas pour les models. \

J'ai enlevé la selection du training set dans le panneau fixe. \

J'ai modifié ma fonction pour upload un training set. \

Je vais à présent essayer de régler le problème de double chargement du classifieur. \

J'ai mis en place un système qui fait en sorte que si on choisit un modèle et un training set, cela fait différents tests par rapport à ces derniers, et puis cela crée le classifieur (essaie) et si cela fonctionne, alors on le récupère comme nouveau classifieur. \
On peut ensuite sauvegarder ce classifieur afin de le charger plus tard pour le réutiliser. \

=== Pour après === \
Par rapport à cela, je dois à présent changer certains affichages pour que cela soit plus clair (sauvegarder et non création). \
Je dois également créer une page pour charger le classifieur dans un onglet séparé. \

Je pourrais faire en sorte qu'il y ait un scroller pour la panneau fixe. \

Fait attention également si une variable classif ne risque pas de rester au mauvais moment. \

Il faut aussi que j'envoie mon projet de poster. \

=== Après Midi === \

Changements des noms pour models (sauvegarde au lieu de création) \

J'ai changé les noms pour les models, et j'ai également changé tout l'affichage pour le chargement du classifieur. \

J'ai ajouté une visualisation au chargement d'un classifieur. \

